on:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 'latest'
            - uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  registry: 'https://npm.pkg.github.com'
